# PROMPT:
# Given the Project table created using the following create script:
# CREATE TABLE jengadb.Project(
#     id INT NOT NULL AUTO_INCREMENT,
#     name VARCHAR (64) NOT NULL,
#     goalDescription VARCHAR (256) NOT NULL,
#     status VARCHAR (32) NOT NULL,
#     userId INT NOT NULL, -- FOREIGN KEY
#     dateTimeCreated datetime DEFAULT CURRENT_TIMESTAMP,
#     dateTimeModified datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
#     PRIMARY KEY (id),
#     FOREIGN KEY (userId) REFERENCES jengadb.User(id)
# )
#
# Generate 100 records with realistic name, goalDescription.
# Valid status values are draft and submitted.
# Randomly assign userId from 1 to 200.
# Realistic project name examples are AI Chatbot, Real Estate Website, AR Glass Landing page.

INSERT INTO jengadb.Project (name, goalDescription, status, userId) VALUES
('AI Chatbot', 'Build a conversational AI chatbot to help users answer common questions.', 'draft', 57),
('Real Estate Website', 'Develop a platform for listing and searching residential properties.', 'submitted', 12),
('AR Glass Landing Page', 'Create a modern landing page to promote the new AR smart glasses product.', 'draft', 88),
('Inventory Management System', 'Design a system to track and manage warehouse inventory.', 'submitted', 143),
('Fitness Tracker App', 'Create a mobile app that monitors daily workouts and calories burned.', 'draft', 35),
('Online Learning Portal', 'Develop a web portal for hosting online courses and student progress tracking.', 'submitted', 101),
('Restaurant Reservation System', 'Build a system that allows users to book tables online.', 'draft', 67),
('E-Commerce Backend API', 'Implement a scalable backend API for an online shopping platform.', 'submitted', 159),
('Crypto Price Monitor', 'Create a dashboard that tracks real-time cryptocurrency prices.', 'draft', 26),
('Task Planner App', 'Develop a productivity app for scheduling tasks and reminders.', 'submitted', 194),
('Event Ticketing System', 'Create a booking system for concerts and live events.', 'draft', 42),
('Smart Home Dashboard', 'Build a central dashboard to manage IoT smart home devices.', 'submitted', 128),
('Online Voting Platform', 'Develop a secure online voting system for internal organization elections.', 'draft', 175),
('Travel Recommendation Engine', 'Implement an AI-powered travel recommendation algorithm.', 'submitted', 6),
('Job Board Website', 'Create a platform where employers can post jobs and applicants can apply.', 'draft', 56),
('Budget Tracking App', 'Develop an app to track personal spending and savings goals.', 'submitted', 187),
('Chat Support Widget', 'Build a lightweight chat widget for website customer support.', 'draft', 92),
('Fleet Management System', 'Design a system to track delivery vehicles and optimize routes.', 'submitted', 141),
('Property Rental App', 'Create an app to list rental units and schedule property viewings.', 'draft', 38),
('HR Onboarding Portal', 'Build a portal that streamlines employee onboarding and documentation.', 'submitted', 199),
('Smart Parking System', 'Develop an IoT-based parking occupancy detection system.', 'draft', 73),
('Online Donation Platform', 'Create a platform for nonprofits to accept donations digitally.', 'submitted', 162),
('VR Museum Tour', 'Build an immersive virtual reality tour for museum exhibits.', 'draft', 49),
('Marketing Analytics Dashboard', 'Design a dashboard to analyze social media and campaign performance.', 'submitted', 118),
('Customer Feedback Collector', 'Create a system to gather and analyze customer product reviews.', 'draft', 9),
('Online Exam System', 'Develop a secure online examination platform with timed assessments.', 'submitted', 137),
('Recipe Recommendation App', 'Build an AI app recommending meals based on available ingredients.', 'draft', 84),
('Warehouse Automation Tool', 'Implement monitoring for warehouse robots and process flow.', 'submitted', 52),
('Booking & Scheduling App', 'Create a scheduling system for service-based businesses.', 'draft', 111),
('Finance Portfolio Tracker', 'Build a tool that manages personal investment portfolios.', 'submitted', 44),
('Digital ID Verification', 'Implement electronic identity verification for user authentication.', 'draft', 173),
('Carpool Matching App', 'Create an app that matches commuters sharing common routes.', 'submitted', 20),
('Knowledge Base Portal', 'Develop an internal self-service documentation system.', 'draft', 64),
('Email Campaign Tool', 'Build an automation tool for sending personalized email campaigns.', 'submitted', 151),
('Company Intranet', 'Create a private corporate intranet for employee communication.', 'draft', 31),
('Pet Care Appointment System', 'Develop a booking system for veterinary clinics and pet grooming.', 'submitted', 176),
('Crowdfunding Platform', 'Build a platform where creators can raise funds for projects.', 'draft', 98),
('Document Approval Workflow', 'Implement a workflow system for document routing and approvals.', 'submitted', 129),
('Online Fitness Coaching', 'Create a platform connecting fitness coaches with clients.', 'draft', 13),
('Parking Slot Locator App', 'Build an app showing available parking spaces in real time.', 'submitted', 183),
('Digital Classroom App', 'Develop a virtual classroom with messaging and assignments.', 'draft', 76),
('Crypto Wallet UI', 'Design a clean user interface for a cryptocurrency wallet.', 'submitted', 147),
('Support Ticketing System', 'Create a helpdesk system for managing customer support tickets.', 'draft', 54),
('Hotel Management System', 'Develop a system for room bookings, housekeeping, and billing.', 'submitted', 191),
('Music Playlist Generator', 'Build an AI tool that creates playlists based on mood.', 'draft', 101),
('Smart Farming Monitor', 'Develop IoT sensors and dashboards to monitor soil and crops.', 'submitted', 124),
('Cloud Backup Utility', 'Create a backup tool that syncs files securely to the cloud.', 'draft', 47),
('Sales CRM Dashboard', 'Build a CRM dashboard for tracking leads and sales performance.', 'submitted', 166),
('Subscription Billing System', 'Implement a billing engine with recurring payments.', 'draft', 29),
('Online Tutoring Marketplace', 'Create a platform that connects students with tutors.', 'submitted', 134),
('AI Resume Analyzer', 'Develop an AI tool to rate and analyze job seekers resumes.', 'draft', 8),
('Team Collaboration App', 'Build a messaging and project collaboration app for teams.', 'submitted', 145),
('Health Monitoring Wearable', 'Design dashboards for wearable health device data.', 'draft', 94),
('Sports Analytics Dashboard', 'Create analytics for team and player performance metrics.', 'submitted', 180),
('News Aggregator App', 'Build an app that curates real-time news from trusted sources.', 'draft', 17),
('Smart Alarm System', 'Develop a mobile-controlled alarm system for home security.', 'submitted', 155),
('Online Portfolio Builder', 'Create a tool for freelancers to build digital portfolios.', 'draft', 61),
('Book Exchange Platform', 'Build a platform allowing users to trade used books.', 'submitted', 133),
('Employee Shift Scheduler', 'Develop a scheduling tool for employee shift management.', 'draft', 23),
('AI Fraud Detector', 'Create an ML model to detect fraudulent transactions.', 'submitted', 197),
('Food Delivery Website', 'Build a platform for ordering food from local restaurants.', 'draft', 78),
('Personal Finance Coach', 'Develop a tool for guiding users toward financial goals.', 'submitted', 163),
('Online Mentorship Platform', 'Create a community for mentors and mentees to connect.', 'draft', 11),
('Gaming Leaderboard System', 'Design a real-time leaderboard for multiplayer games.', 'submitted', 189),
('Smart Lighting Controller', 'Develop an app to manage and schedule home lighting.', 'draft', 45),
('Project Time Tracker', 'Build a time tracking tool for freelancers and teams.', 'submitted', 120),
('Mental Wellness App', 'Create an app promoting mental health exercises and journaling.', 'draft', 82),
('Remote Access Tool', 'Develop software for secure remote access and control.', 'submitted', 172),
('Community Forum Website', 'Build a discussion platform for online communities.', 'draft', 36),
('AI Language Tutor', 'Develop a language-learning app using generative AI.', 'submitted', 140),
('Expense Reimbursement System', 'Create a system for employees to submit and track expenses.', 'draft', 5),
('Online Marketplace', 'Develop a multi-vendor marketplace for buying and selling.', 'submitted', 175),
('Car Rental App', 'Build an app for renting cars and managing reservations.', 'draft', 69),
('IoT Air Quality Monitor', 'Implement sensors and dashboard for air quality tracking.', 'submitted', 116),
('Photo Editing Tool', 'Create a web-based tool for basic and advanced photo editing.', 'draft', 25),
('Project Analytics Engine', 'Build advanced reporting for project metrics and KPIs.', 'submitted', 153),
('SaaS Billing Dashboard', 'Develop dashboards for SaaS subscription and churn metrics.', 'draft', 59),
('Language Translation API', 'Create an API for machine language translation.', 'submitted', 193),
('Customer Loyalty App', 'Build an app that rewards customer engagement.', 'draft', 40),
('Community Event Finder', 'Develop a platform showing local activities and events.', 'submitted', 107),
('Home Budget Planner', 'Create a tool for managing household budgets.', 'draft', 31),
('Electric Vehicle Charging Map', 'Build a map showing nearby EV charging stations.', 'submitted', 170),
('Personal Knowledge Base', 'Create a private wiki for personal notes and ideas.', 'draft', 66),
('Delivery Tracking System', 'Implement package tracking with live status updates.', 'submitted', 144),
('Volunteer Management App', 'Develop a platform to coordinate volunteers and events.', 'draft', 21),
('Digital Storefront Builder', 'Build a drag-and-drop storefront creator for small businesses.', 'submitted', 158),
('Mood Journal App', 'Create a diary app for tracking mood and stress levels.', 'draft', 87),
('Remote Hiring Portal', 'Develop a hiring system with video interview integration.', 'submitted', 130),
('Carbon Footprint Tracker', 'Build a tool to help users reduce carbon emissions.', 'draft', 74),
('Online Gaming Store', 'Develop a platform to buy and redeem digital game codes.', 'submitted', 185),
('Smart Thermostat App', 'Build an app for controlling smart thermostats.', 'draft', 14),
('Team OKR Management Tool', 'Create a system for tracking objectives and key results.', 'submitted', 126),
('Password Manager', 'Develop a secure password storage and autofill tool.', 'draft', 53);
