INSERT INTO jengadb.Skillset (memberId, skill, category, description, level) VALUES
(4, 'Node.js', 'Backend', 'Develops scalable backend services using Node.js.', 'Advanced'),
(5, 'SQL Optimization', 'Database', 'Skilled in writing efficient SQL queries and tuning performance.', 'Proficient'),
(6, 'Docker', 'DevOps', 'Experienced in containerizing applications using Docker.', 'Intermediate'),
(7, 'AWS Cloud Architecture', 'Cloud', 'Designs resilient cloud systems using AWS services.', 'Advanced'),
(8, 'Data Analysis', 'Analytics', 'Performs in-depth data exploration using Python and spreadsheets.', 'Proficient'),
(9, 'Kotlin', 'Mobile Development', 'Builds reliable Android apps with Kotlin.', 'Intermediate'),
(10, 'Agile Project Management', 'Management', 'Coordinates agile workflows and sprints effectively.', 'Expert'),
(11, 'Machine Learning', 'AI/ML', 'Implements ML models for forecasting and classification tasks.', 'Advanced'),
(12, 'Cybersecurity Fundamentals', 'Security', 'Applies secure coding practices and risk mitigation strategies.', 'Beginner'),
(13, 'C# .NET', 'Programming', 'Creates robust enterprise apps using C# and .NET frameworks.', 'Proficient'),
(14, 'GraphQL', 'API Development', 'Designs efficient schemas and queries using GraphQL.', 'Intermediate'),
(15, 'Vue.js', 'Frontend', 'Develops dynamic UI components using Vue.js.', 'Advanced'),
(16, 'Terraform', 'Infrastructure as Code', 'Automates cloud infrastructure provisioning with Terraform.', 'Proficient'),
(17, 'Business Analysis', 'Business', 'Analyzes requirements and translates them into technical specifications.', 'Expert'),
(18, 'Rust Programming', 'Programming', 'Writes high-performance applications using Rust.', 'Intermediate'),
(19, 'CI/CD Pipelines', 'DevOps', 'Builds automated deployments using GitHub Actions and Jenkins.', 'Advanced'),
(20, 'Adobe Illustrator', 'Design', 'Creates vector graphics and design assets for digital products.', 'Proficient'),
(21, 'Unity Game Development', 'Game Dev', 'Builds interactive game mechanics using Unity and C#.', 'Beginner'),
(22, 'MongoDB', 'Database', 'Designs NoSQL schemas and handles scalable data operations.', 'Proficient'),
(23, 'Penetration Testing', 'Security', 'Conducts ethical hacking tests to identify system vulnerabilities.', 'Advanced'),
(24, 'TypeScript', 'Programming', 'Develops large-scale apps with strong typing using TypeScript.', 'Expert'),
(25, 'Project Coordination', 'Management', 'Supports cross-team communication and resource planning.', 'Intermediate'),
(26, 'Flutter', 'Mobile Development', 'Creates responsive mobile apps with Flutter and Dart.', 'Proficient'),
(27, 'Power BI', 'Analytics', 'Builds visual dashboards and reports in Power BI.', 'Advanced'),
(28, 'Redis', 'Caching', 'Implements caching strategies using Redis for performance boosts.', 'Intermediate'),
(29, 'Go (Golang)', 'Programming', 'Develops efficient microservices using Go.', 'Advanced'),
(30, 'Scrum Facilitation', 'Management', 'Leads Scrum ceremonies and supports agile adoption.', 'Expert'),
(31, 'HTML & CSS', 'Frontend', 'Builds accessible web interfaces using modern HTML and CSS standards.', 'Proficient'),
(32, 'Kubernetes', 'DevOps', 'Manages container orchestration using Kubernetes clusters.', 'Advanced'),
(33, 'Data Engineering', 'Data', 'Builds pipelines for ETL and large-scale data processing.', 'Expert'),
(34, 'Selenium Automation', 'QA', 'Creates robust automated UI tests with Selenium.', 'Intermediate'),
(35, 'IT Support', 'Support', 'Provides technical troubleshooting and end-user assistance.', 'Beginner'),
(36, 'Swift', 'Mobile Development', 'Develops iOS applications using Swift and Xcode.', 'Proficient'),
(37, 'Product Strategy', 'Business', 'Defines product roadmaps and prioritizes features based on impact.', 'Advanced'),
(38, 'Blockchain Development', 'Blockchain', 'Builds smart contracts and decentralized apps.', 'Intermediate'),
(39, 'Network Administration', 'IT Infrastructure', 'Manages routers, switches, and enterprise network setups.', 'Proficient'),
(40, 'JIRA Administration', 'Management', 'Sets up workflows, dashboards, and boards in JIRA.', 'Advanced'),
(41, '3D Modeling', 'Design', 'Creates 3D assets using Blender and other modeling tools.', 'Beginner'),
(42, 'PHP Laravel', 'Backend', 'Builds RESTful backends using Laravel and modern PHP.', 'Proficient'),
(43, 'Testing & QA', 'Quality Assurance', 'Executes detailed test plans to ensure product stability.', 'Advanced'),
(44, 'SAP ERP', 'Enterprise Software', 'Works with SAP modules for business process optimization.', 'Intermediate'),
(45, 'Digital Marketing', 'Marketing', 'Runs SEO, PPC, and social media optimization campaigns.', 'Advanced'),
(46, 'Big Data Processing', 'Data', 'Uses Hadoop and Spark to process large-scale datasets.', 'Expert'),
(47, 'Robotics Programming', 'Robotics', 'Programs robotic systems using ROS and sensor integration.', 'Intermediate'),
(48, 'Copywriting', 'Content', 'Writes engaging marketing and product content.', 'Proficient'),
(49, 'Systems Design', 'Architecture', 'Designs scalable software system architectures.', 'Expert'),
(50, 'TensorFlow', 'AI/ML', 'Builds deep learning models using TensorFlow and Keras.', 'Advanced');
