-- SQL Script to insert 100 Project records into jengadb.Project

-- Seed for reproducibility (optional)
-- SET @seed = 42;

-- Helper function to generate a random number within a range
-- SELECT FLOOR(1 + (RAND() * 200)); -- Generates a random integer between 1 and 200

-- *** 50 Records with status 'Draft' ***

INSERT INTO jengadb.Project (name, goalDescription, status, fkUserId) VALUES
('Website Redesign', 'Revamp the company website with a modern, responsive design and improved user experience.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Mobile App MVP', 'Develop the Minimum Viable Product for the new social networking mobile application.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Data Migration Strategy', 'Plan and document the strategy for migrating legacy data to the new cloud database platform.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Q3 Marketing Campaign', 'Outline the strategy and creative assets for the third-quarter promotional marketing campaign.', 'Draft', FLOOR(1 + (RAND() * 200))),
('API Performance Testing', 'Define test cases and metrics for stress testing the primary user authentication API endpoints.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Customer Onboarding Flow', 'Design a simplified and automated onboarding sequence for new enterprise customers.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Internal Tool Refactoring', 'Initial review and plan to refactor the legacy internal analytics reporting tool.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Security Audit Prep', 'Prepare all documentation and configurations necessary for the annual security compliance audit.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Content Strategy Update', 'Draft a new content calendar and identify key topics for the next six months of blog posts.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Cloud Cost Optimization', 'Identify opportunities and implement quick wins to reduce monthly cloud infrastructure spending.', 'Draft', FLOOR(1 + (RAND() * 200))),
('HR System Integration', 'Plan the technical integration between the new HR management system and the payroll software.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Product Feature X Spec', 'Write the detailed functional specification document for the upcoming "Feature X".', 'Draft', FLOOR(1 + (RAND() * 200))),
('Warehouse Inventory System', 'Initial requirements gathering for a new automated inventory tracking system for the warehouse.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Sales Team Training Module', 'Develop the curriculum and materials for the new product training module for the sales team.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Desktop App Bug Fixing Sprint', 'Prioritize and fix critical and major bugs found in the latest release of the desktop application.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Automated Reporting Tool', 'Develop a script to automatically generate and distribute weekly performance reports.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Payment Gateway Research', 'Research and evaluate potential alternative payment gateway providers for international transactions.', 'Draft', FLOOR(1 + (RAND() * 200))),
('User Feedback Analysis', 'Analyze and categorize all incoming user feedback from the last quarter to inform product decisions.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Internal Knowledge Base', 'Establish a structure and start populating content for the new internal documentation knowledge base.', 'Draft', FLOOR(1 + (RAND() * 200))),
('DevOps Pipeline Improvement', 'Investigate and prototype improvements to the continuous integration/continuous deployment (CI/CD) pipeline speed.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Partnership Agreement Draft', 'Draft the initial terms and scope for the strategic partnership with Vendor B.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Compliance Document Review', 'Review and update all privacy and data handling compliance documents to meet new regulations.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Infrastructure Monitoring Setup', 'Configure new dashboards and alerts for critical server performance metrics.', 'Draft', FLOOR(1 + (RAND() * 200))),
('SEO Strategy Refresh', 'Identify new keywords and content gaps to refresh the overall Search Engine Optimization strategy.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Customer Support Scripts', 'Create standardized response scripts and templates for common customer support inquiries.', 'Draft', FLOOR(1 + (RAND() * 200))),
('UI Component Library Update', 'Audit and plan the update of all core UI components to the latest design system standards.', 'Draft', FLOOR(1 + (RAND() * 200))),
('System Scalability Test', 'Plan a series of load tests to determine the current system\'s maximum user capacity.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Video Tutorial Series', 'Outline and script a series of short video tutorials for key product features.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Budget Allocation Review', 'Review and propose adjustments to the departmental budget allocations for the next fiscal year.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Hardware Procurement Plan', 'Create a purchase order plan for new workstation hardware for the development team.', 'Draft', FLOOR(1 + (RAND() * 200))),
('A/B Test Strategy', 'Define the goals and variations for the next set of A/B tests on the checkout page.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Internal Hackathon Organization', 'Draft the rules, themes, and schedule for the upcoming company-wide internal hackathon.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Database Index Optimization', 'Analyze slow queries and propose new indexes to improve database read performance.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Email Newsletter Template', 'Design and implement a new responsive HTML template for the weekly customer email newsletter.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Training Program Certification', 'Develop a structured certification process for employees completing the advanced training program.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Global Launch Strategy', 'Draft a high-level plan for launching the product in new international markets.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Salesforce Customization', 'Gather requirements for customizing the Salesforce CRM to better suit the new sales process.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Accessibility Audit', 'Conduct an initial audit of the primary application interface for WCAG compliance issues.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Documentation Translation', 'Plan the translation and localization of key user documentation into Spanish and French.', 'Draft', FLOOR(1 + (RAND() * 200))),
('New Logo Design Concepts', 'Brainstorm and sketch initial concepts for a potential company logo refresh.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Office Move Planning', 'Coordinate logistics and technical requirements for the upcoming office relocation.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Vendor Management System', 'Define requirements for a centralized system to manage contracts and performance of external vendors.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Tech Debt Reduction Plan', 'Identify and prioritize key areas of technical debt for focused remediation in the next sprint.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Internal Communications Policy', 'Draft a new policy outlining best practices for company-wide internal email and chat usage.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Referral Program Design', 'Design the mechanics, rewards, and tracking system for a new customer referral program.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Automated Testing Framework', 'Select and set up a new framework for end-to-end automated UI testing.', 'Draft', FLOOR(1 + (RAND() * 200))),
('API Documentation Overhaul', 'Restructure and update the public-facing API documentation using a new toolset.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Serverless Migration Analysis', 'Analyze the feasibility and cost savings of migrating key services to a serverless architecture.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Code Review Guidelines', 'Draft and socialize a comprehensive set of guidelines for performing peer code reviews.', 'Draft', FLOOR(1 + (RAND() * 200))),
('Subscription Tier Review', 'Analyze current subscription tiers and propose adjustments to pricing and included features.', 'Draft', FLOOR(1 + (RAND() * 200)));

-- *** 50 Records with status 'Submitted' ***

INSERT INTO jengadb.Project (name, goalDescription, status, fkUserId) VALUES
('Launch Feature Alpha', 'Complete all development, testing, and deployment steps for the private alpha launch of the new feature.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Annual Financial Report', 'Finalize and submit the audited financial report for the previous fiscal year to the board.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('New Employee Handbook', 'Review, approve, and distribute the updated employee handbook reflecting all new HR policies.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Server Uptime Upgrade', 'Successfully upgrade the primary production server operating system and verify 100% uptime post-migration.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Product Launch Event', 'Execute the successful virtual product launch event, achieving a target attendance of 5,000 registrants.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Patent Application Filing', 'Complete all necessary legal review and file the final patent application for the core algorithm.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('ISO 9001 Certification', 'Complete all stages of the external audit and successfully obtain the ISO 9001 quality management certification.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Major System Decommissioning', 'Successfully shut down and remove the retired legacy billing system without any service disruption.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Integration with Partner C', 'Finalize and deploy the full technical integration allowing data exchange with Partner C\'s platform.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Pilot Program Conclusion', 'Conclude the three-month pilot program with initial customers and compile the final success report.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Mass Email Infrastructure', 'Migrate all marketing and transactional email services to the new, high-volume infrastructure.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Employee Satisfaction Survey', 'Distribute, collect, and analyze results from the annual company-wide employee satisfaction survey.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Backend Service Containerization', 'Migrate the core backend microservice to run entirely within a Docker/Kubernetes environment.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Series B Funding Documentation', 'Prepare and submit all required financial and legal documentation for the Series B investment round.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Internal Security Training', 'Conduct the mandatory annual security awareness and phishing training for all employees.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Website Localized for Germany', 'Complete the full translation, localization, and launch of the website for the German market.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('GDPR Compliance Update', 'Implement all necessary technical and procedural changes to ensure full GDPR compliance.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('New Hire Batch Onboarding', 'Successfully onboard and train the new cohort of 15 hires across various departments.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('API Version 2.0 Release', 'Deploy and fully deprecate the old endpoints, making API v2.0 the primary interface for all users.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Data Warehouse Implementation', 'Complete the setup, ETL pipeline creation, and initial data load for the new central data warehouse.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Public Relations Campaign', 'Execute the planned PR campaign, securing coverage in at least 5 major industry publications.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Recruitment Software Selection', 'Finalize the evaluation, negotiation, and selection of the new Applicant Tracking System (ATS).', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Automated Code Linting', 'Integrate a new automated code linting and style checking tool into the CI pipeline.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Customer Success Program', 'Launch the new tiered customer success program, migrating all existing customers into the appropriate tiers.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('System Penetration Test', 'Complete the external penetration test by a third-party vendor and remediate all critical findings.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('New Product Packaging', 'Finalize design, manufacturing, and distribution of the new environmentally friendly product packaging.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Dashboard Analytics Overhaul', 'Migrate all key business intelligence dashboards to the new BI platform for improved performance.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Disaster Recovery Drill', 'Successfully execute the annual disaster recovery simulation drill and document the results.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Annual Performance Reviews', 'Complete the full cycle of annual employee performance reviews and compensation adjustments.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Third-Party Software Audit', 'Complete the audit of all third-party software licenses and usage compliance.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Cloud Region Expansion', 'Successfully deploy core services into a new cloud region (e.g., EU-Central) for redundancy and compliance.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Internal Tools Migration', 'Migrate all users and data from the old internal ticketing system to the new service desk platform.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Financial System Upgrade', 'Complete the necessary upgrade and patching of the main corporate accounting software.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('User Interface Polish', 'Apply final design polish and performance optimizations across the entire primary application UI.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Open Source Contribution', 'Finalize and submit the company\'s first major contribution to a key open-source project.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Team Restructuring', 'Implement the planned restructuring of the Engineering and Product departments.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Compliance Reporting', 'Generate and submit all required quarterly regulatory compliance reports to the governing bodies.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Product Documentation Release', 'Publish the comprehensive updated user manual and technical specifications for the latest release.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Office Network Overhaul', 'Replace all aging network switches and routers with new, high-speed, managed hardware.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('External Consultant Project', 'Conclude the scope of work with external consultants on the supply chain optimization project.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Mobile App Store Submission', 'Successfully submit and get approval for the latest version of the mobile application on both major app stores.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Data Anonymization Pipeline', 'Implement the automated process to anonymize production user data for use in testing environments.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Customer Win-Back Campaign', 'Execute the targeted email and outreach campaign aimed at reactivating dormant customer accounts.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Accessibility Remediation', 'Implement all technical changes identified in the accessibility audit to achieve WCAG 2.1 AA compliance.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Vendor Contract Renegotiation', 'Successfully renegotiate and finalize the contract terms with the primary hosting provider.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Cross-Team Knowledge Transfer', 'Complete the scheduled knowledge transfer sessions between the Backend and Frontend teams.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Internal Metric Standardization', 'Define, implement, and document standardized definitions for all core business metrics.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('User Permissions System', 'Fully deploy and test the new granular user permissions and role management system.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('End-of-Year System Audit', 'Complete the technical and procedural audit of all critical systems before the year-end freeze.', 'Submitted', FLOOR(1 + (RAND() * 200))),
('Customer Satisfaction Target', 'Achieve and sustain a Customer Satisfaction (CSAT) score of 95% or higher for the full quarter.', 'Submitted', FLOOR(1 + (RAND() * 200)));