USE jengadb;

DROP TABLE IF EXISTS User;
CREATE TABLE User (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    role ENUM('regular', 'admin') NOT NULL DEFAULT 'regular',
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Member;
CREATE TABLE Member (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Project;
CREATE TABLE Project (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    requirementDescription TEXT,
    goalDescription TEXT,
    status ENUM('draft', 'submitted') NOT NULL DEFAULT 'draft',
    userId BIGINT NOT NULL,
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Budget;
CREATE TABLE Budget (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    projectId BIGINT NOT NULL,
    floor DECIMAL(10, 2) NOT NULL,
    ceiling DECIMAL(10, 2) NOT NULL,
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Timeframe;
CREATE TABLE Timeframe (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    projectId BIGINT NOT NULL COMMENT 'FK to Project table',
    startTime DATETIME NOT NULL,
    endTime DATETIME NOT NULL,
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Team;
CREATE TABLE Team (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    projectId BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS TeamMember;
CREATE TABLE TeamMember (
    teamId BIGINT NOT NULL,
    memberId BIGINT NOT NULL,
    PRIMARY KEY (teamId, memberId),
    FOREIGN KEY (teamId) REFERENCES Team(id) ON DELETE CASCADE,
    FOREIGN KEY (memberId) REFERENCES Member(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Skillset;
CREATE TABLE Skillset (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    memberId BIGINT NOT NULL,
    skill VARCHAR(100) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    level VARCHAR(50),
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (memberId) REFERENCES Member(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Prompt;
CREATE TABLE Prompt (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    projectId BIGINT NOT NULL,
    prompt TEXT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS GenerationHistory;
CREATE TABLE GenerationHistory (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    projectId BIGINT NOT NULL,
    promptId BIGINT NOT NULL,
    llmResponse TEXT NOT NULL,
    dateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE,
    FOREIGN KEY (promptId) REFERENCES Prompt(id) ON DELETE CASCADE
);